pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Use SSH URL and specify the credentialsId
                git credentialsId: '70794d5b-e35-40db-9ce6-73f016e30d28', url: 'git@github.com:shivam-tayade/hello-world-java.git'
            }
        }

        stage('Compile') {
            steps {
                script {
                    sh 'javac HelloWorld.java'
                }
            }
        }

        stage('Run') {
            steps {
                script {
                    sh 'java HelloWorld'
                }
            }
        }
    }

    post {
        success {
            echo 'Java HelloWorld program executed successfully!'
        }
        failure {
            echo 'The pipeline failed!'
        }
    }
}
